# -*- coding: utf-8 -*-
"""Copy of Titanic EDA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jKHAFrl0EgomUbmUtxukYfjX82Jkb4jS
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

from google.colab import files

files = files.upload()

import io

df = pd.read_csv(io.BytesIO(files['titanic_train.csv']))

df.head()

df.isnull()

import seaborn as sns

sns.heatmap(df.isnull(),yticklabels=False,cbar=False,cmap='viridis')

sns.set_style("whitegrid")
sns.countplot(x='Survived',data=df)

sns.set_style('whitegrid')
sns.countplot(x='Survived', hue='Sex', data=df, palette='RdBu_r')

sns.set_style('whitegrid')
sns.countplot(x='Survived', hue='Pclass', data=df, palette='rainbow')

sns.distplot(df['Age'].dropna(),kde=False, color='darkred', bins=40)

df['Age'].hist(bins=30, color='darkred', alpha=0.3)

sns.countplot(x='SibSp', data=df)

df['Fare'].hist(color='green', bins=40, figsize=(8,4))

plt.figure(figsize=(12,7))
sns.boxplot(x='Pclass', y='Age', data=df, palette='winter')

def impute_age(cols):
  Age = cols[0]
  Pclass= cols[1]

  if pd.isnull(Age):

    if Pclass == 1:
      return 37
    
    elif Pclass == 2:
      return 29

    else:
      return 24

  else:
    return Age

df['Age']= df[['Age','Pclass']].apply(impute_age, axis=1)

sns.heatmap(df.isnull(),yticklabels=False, cbar=False, cmap='viridis')

df.drop('Cabin', axis=1, inplace=True)

df.head()

df.dropna(inplace=True)

pd.get